version: "3"

services:
  ftp-server:
    image: stilliard/pure-ftpd:latest
    volumes:
      - /mydata:/ftp
    ports:
      - 21:21
    environment:
      - FTP_USER=ftp-user
      - FTP_PASS=ftpuser
      - FTP_HOME=/home/ftp-user/ftp
      - FTP_HOST=ftp-server
      - PASV_ADDRESS=ftp-server
    restart: always
    networks:
      - my-network
    
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3306:3306
    networks:
      - my-network
    environment:
     - MYSQL_ROOT_PASSWORD=guessitplease
     - MYSQL_DATABASE=esprithub
     - MYSQL_USER=root
     - MYSQL_PASSWORD=guessitplease
    command: --bind-address=0.0.0.0
    volumes:
      - db_data:/var/lib/mysql
     
    
     
  python_app:
    image: naderbessioud/esprithubpython:latest
    restart: on-failure
    container_name: esprithubpython
    ports:
     - 5000:5000
    networks:
      - my-network
    depends_on:
     - mysqldb
    
  spring_app:
    image: naderbessioud/esprithubspring1:latest
    container_name: esprithubspring1
    restart: on-failure
    networks:
      - my-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/esprithub?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "guessitplease",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "create"
      }'
      
    ports:
     - 8082:8082
    depends_on:
     - mysqldb
     - ftp-server
    
  angular_app:
    image: naderbessioud/esprithubangular:latest
    container_name: esprithubangular
    restart: on-failure
    ports:
     - 4200:80
    networks:
      - my-network
    depends_on:
     - spring_app
     - python_app
volumes:
 db_data:
networks:
  my-network:
