version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    ports:
     - 3308:3308
    environment:
     - MYSQL_ROOT_PASSWORD=0000
     - MYSQL_DATABASE=esprithub
     - MYSQL_USER=nader
     - MYSQL_PASSWORD=0000
     expose:
     - 3308
     
  python_app:
    image: naderbessioud/esprithubpython:latest
    container_name: esprithubpython
    ports:
     - 5000:5000
    
  spring_app:
    image: naderbessioud/esprithubspring1:latest
    container_name: esprithubspring
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3308/esprithub?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
     - 8083:8083
    depends_on:
     - mysqldb
    
  angular_app:
    image: naderbessioud/esprithubangular:latest
    container_name: esprithubangular
    restart: on-failure
    ports:
     - 4200:80
    depends_on:
     - spring_app
     - python_app
